---
- name: Posibolt Setup
  hosts: pbolt
  vars:

        Seed_DB: Posibolt_SA_2021Mar1_1394.cdmp
        DB_Name: testing27
        # DB_User: adempiere
        Missing_SQL_File: navicareSQL_22JULY21.zip
        Remote_Release_Path: /home/posibolt/Release
        Postgres_Home: /opt
        User: posibolt
        Adempiere_Ubuntu_zip: Adempiere.zip
        Adempiere_CentOS_zip: Adempiere_Centos.zip
        Adempiere_lib_file: Files.zip


  tasks: 

    - name: cheking db user
      shell: "{{ Postgres_Home }}/PostgreSQL/9.5/bin/psql -lqt | cut -d '|' -f 2 | grep -w testing"
      become: true
      become_user: postgres
      register: db_user_out
      failed_when: db_user_out.rc == 2

    - debug:
       var: db_user_out.stdout_lines

    - name: udb user create
      shell: "{{ Postgres_Home }}/PostgreSQL/9.5/bin/createuser -s -U postgres testing"
      args:
        executable: /bin/bash 
      when: db_user_out.rc == 1
      register: dbusercreate_out

    - debug:
        var: dbusercreate_out.stdout_lines

    - name: chekig
      shell: "{{ Postgres_Home }}/PostgreSQL/9.5/bin/psql -lqt | cut -d '|' -f 1 | grep -w {{ DB_Name }}"
      become: true
      become_user: postgres
      register: command_out
      failed_when: command_out.rc == 2
    
    - debug:
        var: command_out.stdout_lines

    - name: create db
      shell: "{{ Postgres_Home }}/PostgreSQL/9.5/bin/createdb -U adempiere -E UTF8 -T template0 {{ DB_Name }}"
      when: command_out.rc == 1
      register: dbcreate_out

    - debug: 
        var: dbcreate_out.stdout_lines
